perspiring-farkleberry/grace-shopper

package.json
=> package name updated

server/db/models/animal.js, server/db/models/cartItem.js, server/db/models/index.js, server/db/models/user.js
=> Added Sequelize models for CartItem, Animal and added fields to User

server/db/models/animal.js, server/db/models/index.js
=> fixed sequelize bug

package.json
=> package json updates

package.json
=> bug fix for heroku

client/components/navbar.js, package-lock.json, package.json, public/index.html
=> now requires react semantic ui

.travis.yml, README.md, package-lock.json, package.json
=> travis integration should work

client/components/navbar.js, public/style.css
=> navbar needs logout functionality, maybe also a logo if we add one

client/components/Cards/checkoutSummaryCard.js, client/components/Cards/itemCardCart.js, client/components/index.js, package-lock.json
=> card components

server/db/db.js
=> test updates

client/components/Cards/ProductList.js, client/components/Cards/SingleProductCard.js, public/style.css
=> updated single product card

client/components/Cards/checkoutSummaryCard.js, client/components/Cards/itemCardCart.js, client/components/index.js, client/components/navbar.js, client/components/user-home.js, client/routes.js
=> Cards folder

client/store/cartItems.js, package-lock.json, server/api/cart.js, server/api/index.js
=> cart-items-reducer

client/store/animals.js, server/api/animals.js, server/api/index.js
=> api route working, redux hopefully also working

client/components/Cards/ProductList.js
=> hopefully redux working pending store setup

server/api/users.js
=> updated users api

client/components/Cards/ProductList.js
=> Map animals

server/api/users.js
=> heroku bug fix attempt

package.json
=> fix bug plz

client/components/NavCart.js, client/components/navbar.js, client/store/cart.js
=> stateful nav cart component

client/app.js, client/components/navbar.js, client/routes.js
=> new routes and links

client/app.js, client/components/NavCart.js, client/components/navbar.js, client/routes.js
=> react routes update

client/components/Cards/SingleProductCard.js, public/style.css
=> tweaked single product card

client/components/Cards/SingleProductCard.js
=> removed commented code

client/components/Cards/SingleProductCard.js, server/api/animals.spec.js, server/api/users.js, server/api/users.spec.js
=> API tests for Animal: GET; User: GET, POST, PUT

script/seed.js
=> updated seed - images

client/components/user-home.spec.js
=> React specs

client/components/Cards/SingleProductCard.js, client/store/cart.js, server/api/cart.js
=> cart semi-working

client/app.js, client/components/Cards/ModalContainer.js, client/components/Cards/ProductList.js, client/components/Cards/SingleProductCard.js, client/components/Cards/WelcomeCard.js, client/components/Main.js, client/routes.js, client/store/tests/user.spec.js, client/store/user.js, public/style.css, server/auth/google.js
=> inserted welcome modal for guest checkout

client/components/Cards/ProductList.js, client/components/Cards/SingleProductCard.js
=> semi-functional cart

client/components/Cards/SingleProductCard.js, client/components/auth-form.js, client/store/user.js, server/auth/google.js
=> Hopefully working! Andrew testing

client/components/Cards/checkoutSummaryCard.js, client/components/Checkout.js, client/components/StripeCheckout.js, client/components/ViewCart.js, client/routes.js, client/store/checkout.js, package-lock.json, package.json, public/index.html, public/style.css
=> stripe test functionality added

client/components/Cards/SingleProductCard.js, server/api/cart.js, server/db/models/cartItem.js
=> cart push/post working

client/app.js, client/components/EditProfileForm.js, client/components/RenderField.js, client/components/ViewProfile.js, client/components/navbar.js, client/routes.js, client/store/forms.js, client/store/index.js, client/store/user.js, package-lock.json, package.json, server/api/users.js
=> partially finished view and edit profile form

client/components/StripeCheckout.js, server/api/index.js, server/api/stripe.js
=> added stripe test functionality with checkout component

client/components/Cards/OrderHistoryCard.js, client/components/Cards/OrderHistoryItemCard.js, client/components/ViewProfile.js, package-lock.json, public/style.css
=> order history components/cards

server/api/users.js
=> fixed api user put request

client/components/Cards/SingleProductCard.js, client/store/cart.js, public/style.css
=> add to cart message

client/components/EditProfileForm.js, client/components/ViewProfile.js, client/store/forms.js
=> revised approach to edit profile form

client/components/EditProfileForm.js, public/style.css
=> css styling for edit form (added classNames)

client/components/Cards/SingleProductCard.js, client/components/CheckoutPage.js, client/components/NavCart.js, client/store/cart.js, server/api/cart.js, server/db/models/cartItem.js, server/db/models/index.js
=> edited cart-item model associations, api routes

client/components/CheckoutPage.js, client/components/StripeCheckout.js, client/routes.js, client/store/cart.js, server/api/cart.js
=> checkout page connected

server/api/cart.js
=> edited api route for cart

client/components/Cards/checkoutSummaryCard.js, client/components/CheckoutPage.js, client/components/EditProfileForm.js, client/components/NavCart.js, client/components/ViewCart.js, client/store/user.js
=> form with disabled button for address

server/api/index.js, server/api/order.js
=> checkout form

client/components/CheckoutPage.js, client/store/forms.js
=> updated edit modal on checkout page

client/app.js, client/components/Cards/ItemCartCard.js, client/components/Cards/ProductList.js, client/components/Cards/SingleProductCard.js, client/components/ViewCart.js, client/routes.js, client/store/cart.js, server/api/cart.js
=> added cart functionality for logged in and guest users

client/components/ViewCart.js
=> removed rogue div in ViewCart

client/components/Cards/checkoutSummaryCard.js, client/components/ViewCart.js
=> cart summary now 100% more functional

client/components/navbar.js, client/store/cart.js
=> fixed some guest cart mechanics

client/store/cart.js
=> for real this time

client/components/Cards/OrderHistoryCard.js, client/components/Cards/OrderHistoryItemCard.js, client/components/ViewProfile.js, client/store/index.js, client/store/order.js, public/style.css, server/api/order.js, server/db/models/order.js
=> order history list

client/components/Cards/BitcoinCheckout.js, client/components/Checkout.js, client/components/CheckoutPage.js, client/routes.js, public/style.css
=> fixed login welcome modal issue

client/components/Cards/ItemCartCard.js, public/style.css
=> css minor style changes

client/components/CheckoutPage.js, client/store/cart.js, server/api/cart.js
=> edited paid message to render on checkout

client/components/ViewCart.js, client/store/cart.js
=> guest cart actually 100% functional

client/components/AddNewUserForm.js, client/components/Cards/OrderHistoryCard.js, client/components/CheckoutPage.js, client/components/StripeCheckout.js, client/components/ViewProfile.js, client/components/navbar.js
=> success page for registered user, navbar home link

client/components/CheckoutPage.js, client/components/GuestCheckout.js, client/components/GuestInfoForm.js, client/components/StripeCheckout.js, client/routes.js, client/store/cart.js, client/store/user.js, server/api/cart.js
=> added checkout functionality for guest user

client/components/Cards/ItemCartCard.js, client/components/ViewCart.js, client/store/cart.js, server/api/cart.js
=> built cart delete functionality for logged in and guest users

client/components/Cards/ItemCartCard.js, client/components/Cards/SingleProductCard.js
=> built quantity validation

client/components/CheckoutPage.js, client/components/CheckoutSuccess.js, client/components/GuestCheckout.js, client/components/StripeCheckout.js, client/components/UserSignUp.js, client/store/user.js, public/style.css, server/auth/index.js
=> completed guest checkout functionality

README.md
=> fixed bullet points

client/components/Cards/SingleProductCard.js, server/api/cart.js
=> broke the animation of the add to cart button

client/components/Cards/BitcoinCheckout.js, client/components/GuestCheckout.js, package-lock.json, package.json, public/style.css
=> added coinbase functionality

client/components/Cards/ItemCartCard.js, client/components/Cards/checkoutSummaryCard.js, client/components/ViewCart.js, package-lock.json, public/style.css
=> read more/read less btns

client/components/Cards/SingleProductCard.js, server/api/cart.js
=> secured api routes to use req.user and not req.params

client/components/Cards/SingleProductCard.js, public/style.css
=> home page layout css

client/components/Cards/ItemCartCard.js, client/components/CheckoutSuccess.js, client/components/StripeCheckout.js, client/components/ViewCart.js, client/store/cart.js, server/api/cart.js
=> fixed route bugs, added update functionality

client/components/Cards/SingleProductCard.js, client/components/GuestCheckout.js, client/components/Main.js, client/components/auth-form.js, public/style.css
=> welcome-modal-single-desc

client/components/Cards/ItemCartCard.js, client/components/Cards/checkoutSummaryCard.js, client/components/CheckoutPage.js, client/components/ViewCart.js, public/style.css
=> checkout css

client/components/Cards/ItemCartCard.js, client/components/Cards/checkoutSummaryCard.js, client/components/CheckoutPage.js, client/components/ViewCart.js, client/store/user.js, public/style.css
=> Desc to item

client/components/CheckoutPage.js, client/components/GuestCheckout.js, client/components/UserSignUp.js, public/style.css, server/db/models/order.js
=> order model checkout success

client/components/Cards/ItemCartCard.js
=> fixed cart total bug

.gitignore, client/components/Checkout.js, client/components/StripeCheckout.js, package-lock.json, package.json, server/api/stripe.js, webpack.test.config.js
=> fixed webpack issues
